name: MelissaAusili.com
favicon: null
layout_spectrum: 0.8723054963629693
typography_spectrum: 0.6302602346986532
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6298809936270118
  lightness: 0.6853889203630388
  saturation: 0.5571737941354513
  rhythmicContrast: 0.7729759491048753
purpose: []
